ALTER TABLE books ADD COLUMN title_transcription TEXT;
ALTER TABLE books ADD COLUMN series_title TEXT;
ALTER TABLE books ADD COLUMN series_title_transcription TEXT;
ALTER TABLE books ADD COLUMN alternative TEXT;
ALTER TABLE books ADD COLUMN alternative_transcription TEXT;
ALTER TABLE books ADD COLUMN volume TEXT;
ALTER TABLE books ADD COLUMN volume_transcription TEXT;
ALTER TABLE books ADD COLUMN price TEXT;
ALTER TABLE books ADD COLUMN extent TEXT;
ALTER TABLE books ADD COLUMN jpno TEXT;
ALTER TABLE books ADD COLUMN ndl_url TEXT;
ALTER TABLE books ADD COLUMN isdn_region TEXT;
ALTER TABLE books ADD COLUMN isdn_class TEXT;
ALTER TABLE books ADD COLUMN isdn_type TEXT;
ALTER TABLE books ADD COLUMN isdn_rating_gender TEXT;
ALTER TABLE books ADD COLUMN isdn_rating_age TEXT;
ALTER TABLE books ADD COLUMN isdn_genre_code TEXT;
ALTER TABLE books ADD COLUMN isdn_genre_name TEXT;
ALTER TABLE books ADD COLUMN isdn_genre_user TEXT;
ALTER TABLE books ADD COLUMN isdn_c_code TEXT;
ALTER TABLE books ADD COLUMN isdn_author TEXT;
ALTER TABLE books ADD COLUMN isdn_shape TEXT;
ALTER TABLE books ADD COLUMN isdn_contents TEXT;
ALTER TABLE books ADD COLUMN isdn_barcode2 TEXT;
ALTER TABLE books ADD COLUMN isdn_sample_image_url TEXT;
ALTER TABLE books ADD COLUMN isdn_useroption TEXT;
ALTER TABLE books ADD COLUMN isdn_external_links TEXT;
ALTER TABLE books ADD COLUMN catalog_number TEXT;
ALTER TABLE books ADD COLUMN artist TEXT;
ALTER TABLE books ADD COLUMN label TEXT;
ALTER TABLE books ADD COLUMN disc_count INTEGER;
ALTER TABLE books ADD COLUMN epub_file_hash TEXT;
ALTER TABLE books ADD COLUMN epub_file_name TEXT;
ALTER TABLE books ADD COLUMN reading_status TEXT DEFAULT 'unread';
ALTER TABLE books ADD COLUMN storage_location_id INTEGER REFERENCES storage_locations(id) ON DELETE SET NULL;
ALTER TABLE books ADD COLUMN label_id INTEGER REFERENCES labels(id) ON DELETE SET NULL;
ALTER TABLE books ADD COLUMN created_at TEXT;
ALTER TABLE books ADD COLUMN updated_at TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_books_isdn ON books(isdn) WHERE isdn IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_books_jan ON books(jan) WHERE jan IS NOT NULL;
